<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input value="<?= $this->view->usuario['nome']?>" name="nome" type="text" class="form-control" placeholder="Nome">
              </div>

              <?php if($this->view->arrobaFaltando) {?>
                <small class="form-text text-danger">
                  *Insira um e-mail válido!
                </small>
              <?php } ?>
              
              <div class="form-group">
                <input value="<?= $this->view->usuario['email']?>" name="email" type="text" class="form-control" placeholder="E-mail">
              </div>
              

              <?php if($this->view->valido == false) {?>
                <small class="form-text text-danger">
                  *A senha deve conter pelo menos 5 caracteres!
                </small>
              <?php } ?>

              <div class="form-group">
                <input value="<?= $this->view->usuario['senha']?>" name="senha" type="password" class="form-control" placeholder="Senha">
              </div>

              <?php if($this->view->usuarioExistente == true) {?>
                <small class="form-text text-danger">
                  *Usuário já cadastrado!
                </small>
              <?php } ?>

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

              
              <?php if($this->view->espacoVazio == true) {?>
                <small class="form-text text-danger">
                  *Há campo(s) em branco, preecha(os) e tente novamente.
                </small>
              <?php } ?>
              

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  