<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>
        
        <div class="row">
          <div class="col">

            <form id="inscreverseForm" action="/registrar" method="post">

              <?php if($this->view->emailCadastrado) {?>
                <label id="labelUsuarioExistente" style="color: red;">Usuário já cadastrado</label>
              <?php } ?>

              <div class="form-group ">                
                <input  value="<?= $this->view->usuario['nome'] ?>" name="nome" type="text" class="form-control nome" placeholder="Nome">
              </div>

                            
                <div class="form-group">
                  <input onload="getEmail(this)" onblur="getEmail(this)" onfocus="getEmail(this)" onkeyup="getEmail(this)" value="<?= $this->view->usuario['email'] ?>" name="email" id="email" class="form-control"  aria-describedby="emailHelp" placeholder="E-mail">
                  <label style="color: red;" id="label">E-mail já cadastrado</label> 

                </div>
                
              

              <div class="form-group">                
                <input value="<?= $this->view->usuario['senha'] ?>" name="senha" type="text" class="form-control senha"  placeholder="Senha">
              </div>

              
            

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              
              

                <button disabled="disabled" id="btnSubmit" type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              
              




            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>