

		<div class="col-md-6">
			
			<div class="row mb-2 procurarPorUsuarios">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form id="procurar" method="post" action="/pesquisar_usuarios">
								<div class="input-group mb-3">
									<input name="pesquisarPor" type="text" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>			
		</div>	