
	

		<div class="col-md-6">
			<div class="row mb-2 after">
				<div class="col tweetBox">
					<form id="formTweet" action="/tweet" method="post">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>
					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['nome'] ?></strong> <small><span class="text text-muted">- <?= $tweet['data'] ?></span></small></p>
						<p><?= $tweet['tweet'] ?></p>
						

						<br />
						<?php if($tweet['id_usuario'] == $_SESSION['id']) {?>
							<form id="removerTimeline" method="get" action="/remover_tweet">
								<div class="col d-flex justify-content-end">
									<input id="id" name="id" class="id_usuario" hidden="hiden" value="<?= $tweet['id'] ?>"></input>
									<button class="btn btn-danger removerTweetTimeline"><small>Remover</small></button>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a id="quemSeguir" value="carregar" href="/quem_seguir" class="quemSeguirTxt quem link">Procurar por pessoas conhecidas</a>
			</div>
		</div>

