
	

		<div class="col-md-6">
			<div class="row mb-2 after">
				<div class="col tweetBox">
					<form id="formTweet" action="/tweet" method="post">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>
					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['nome'] ?></strong> <small><span class="text text-muted">- <?= $tweet['data'] ?></span></small></p>
						<p><?= $tweet['tweet'] ?></p>

						<br />
						<form>
							<div class="col d-flex justify-content-end">
								<button type="submit" class="btn btn-danger"><small>Remover</small></button>
							</div>
						</form>
					</div>
				</div>
			<?php } ?>

		</div>



		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a id="quemSeguir" value="carregar" href="/quem_seguir" class="quemSeguirTxt quem link">Procurar por pessoas conhecidas</a>
			</div>
		</div>

