<!doctype html>
<html lang="pt-br">

  <head>
    <title>Twitter</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/98dc572ff8.js" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



    <link rel="stylesheet" type="text/css" href="/css/style.css">
  </head>

  <body class="body">
      
    <nav class="navbar navbar-expand-lg menu">
      <div class="container">
        <div class="navbar-nav">
          <a id="home" class="menuItem home link" href="/timeline">
            Home
          </a>

          <a class="menuItem sair" href="/sair">
            Sair
          </a>
          <img src="/img/twitter_logo.png" class="menuIco" />
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      <div class="row pt-2">
        <div class="col-md-3">
          <div class="perfil">
            <div class="perfilTopo">
            </div>
            <div class="perfilPainel">
              <div class="row mt-2 mb-2">
                <div class="col mb-2">
                  <span class="perfilPainelNome">
                    <?php print_r($this->view->infoUsuario['nome']) ?>
                  </span>
                </div>
              </div>

              <div class="row mb-2">

                <div class="col">
                  <span class="perfilPainelItem">Tweets</span><br />
                  <span class="perfilPainelItemValor">
                    <?php print_r($this->view->totalTweets['total_tweets']) ?>
                  </span>
                </div>

                <div class="col">
                  <span class="perfilPainelItem">Seguindo</span><br />
                  <span class="perfilPainelItemValor">
                    <?php print_r($this->view->totalSeguindo['total_seguindo']) ?>
                  </span>
                </div>

                <div class="col">
                  <span class="perfilPainelItem">Seguidores</span><br />
                  <span class="perfilPainelItemValor">
                    <?php print_r($this->view->totalSeguidores['total_seguidores']) ?>
                  </span>
                </div>
              </div>
            </div>
          </div>
          
        </div>

        <?= $this->content() ?>

      </div>
    </div>




    <script src="/jquery/jquery-3.5.1.min.js"></script>
    <script src="/js/jquery.validate.js"></script>
    <script src="/js/additional-methods.js"></script>
    <script src="/js/localization/messages_pt_BR.js"></script>
    <script src="/js/meuScript.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>